# Generated by Django 4.2.2 on 2023-06-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_location_portfolio_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='location',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='skills',
            field=models.CharField(default='this', max_length=255),
            preserve_default=False,
        ),
    ]
